name: GraalVM Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-scala
        path: | 
          ~/.ivy2/cache
          ~/.sbt      
    - uses: olafurpg/setup-scala@v10
      with: 
        java-version: graalvm@
    - name: Install native-image component
      run: gu install native-image
    - name: Install coursier
      run: brew install coursier/formulas/coursier
    - name: Render plugin
      run: sbt ";clean ;g8Test;"
    - name: Build native plugin
      run: |
        cd target/sbt-test/swiftbar4s.g8/scripted/
        bash -xe build-native.sh
    - name: Run plugin
      run: ./target/sbt-test/swiftbar4s.g8/scripted/myplugin.5s
