name: GraalVM Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-scala
        path: | 
          ~/.ivy2/cache
          ~/.sbt
          ~/Library/Caches/Coursier
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: graalvm@21.0
    - name: Render plugin
      run: sbt ";clean ;g8Test;"
    - name: Build native plugin
      run: |
        cd target/sbt-test/swiftbar4s.g8/scripted/
        sbt nativeImageRunAgent
        sbt nativeImage
    - name: Run plugin
      run: ./target/sbt-test/swiftbar4s.g8/scripted/myplugin
