# This is a basic workflow to help you get started with Actions

name: GraalVM Test

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: '21.0.0.java11'

      - name: Install native-image component
        run: gu install native-image

      - name: Test java
        run: java --version

      - name: Test native image
        run: native-image --help
